// Permission constants for role-based access control
module.exports = {
    // Offer permissions
    MANAGE_OFFER_TEMPLATES: 'MANAGE_OFFER_TEMPLATES',
    CREATE_OFFERS: 'CREATE_OFFERS',
    VIEW_OFFER_HISTORY: 'VIEW_OFFER_HISTORY',
    EDIT_OFFERS: 'EDIT_OFFERS',
    DELETE_OFFERS: 'DELETE_OFFERS',

    // Invoice permissions
    MANAGE_INVOICES: 'MANAGE_INVOICES',
    VIEW_INVOICES: 'VIEW_INVOICES',
    GENERATE_INVOICE_PDF: 'GENERATE_INVOICE_PDF',

    // Settings permissions
    MANAGE_SETTINGS: 'MANAGE_SETTINGS',
    MANAGE_GENERAL_SETTINGS: 'MANAGE_GENERAL_SETTINGS',
    MANAGE_EMAIL_TEMPLATES: 'MANAGE_EMAIL_TEMPLATES',

    // Admin permissions
    MANAGE_SUB_ADMINS: 'MANAGE_SUB_ADMINS',

    // Company & Contact permissions
    MANAGE_COMPANIES: 'MANAGE_COMPANIES',
    MANAGE_CONTACTS: 'MANAGE_CONTACTS',

    // Inventory permissions
    MANAGE_INVENTORY: 'MANAGE_INVENTORY',
    VIEW_INVENTORY: 'VIEW_INVENTORY',

    // Project permissions
    MANAGE_PROJECTS: 'MANAGE_PROJECTS',
    VIEW_PROJECTS: 'VIEW_PROJECTS',
};
